### ISSUE TITLE
Unexpected exception during findElement

### ISSUE THREAD

**Issue by NoodlesNZ** [facebook/php-webdriver#236]
When trying to find an element on a page I get:

```
16:55:41.742 INFO - Creating a new session for Capabilities [{browserName=firefox}]
16:55:43.136 INFO - Done: [new session: Capabilities [{browserName=firefox}]]
16:55:43.138 INFO - Executing: [get: http://www.drugs.com/])
16:55:51.327 INFO - Done: [get: http://www.drugs.com/]
16:55:51.328 INFO - Executing: [find element: By.id: livesearch-main])
16:55:52.255 ERROR - Unexpected exception during findElement
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.openqa.selenium.remote.ErrorHandler$FrameInfoToStackFrame.apply(ErrorHandler.java:297)
	at org.openqa.selenium.remote.ErrorHandler$FrameInfoToStackFrame.apply(ErrorHandler.java:1)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators.addAll(Iterators.java:361)
	at com.google.common.collect.Lists.newArrayList(Lists.java:160)
	at com.google.common.collect.Iterables.toCollection(Iterables.java:337)
	at com.google.common.collect.Iterables.toArray(Iterables.java:315)
	at org.openqa.selenium.remote.ErrorHandler.rebuildServerError(ErrorHandler.java:270)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:118)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:399)
	at org.openqa.selenium.By$ById.findElement(By.java:215)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:102)
	at com.sun.proxy.$Proxy1.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:185)
	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16:55:52.257 WARN - Exception thrown
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.openqa.selenium.remote.ErrorHandler$FrameInfoToStackFrame.apply(ErrorHandler.java:297)
	at org.openqa.selenium.remote.ErrorHandler$FrameInfoToStackFrame.apply(ErrorHandler.java:1)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators.addAll(Iterators.java:361)
	at com.google.common.collect.Lists.newArrayList(Lists.java:160)
	at com.google.common.collect.Iterables.toCollection(Iterables.java:337)
	at com.google.common.collect.Iterables.toArray(Iterables.java:315)
	at org.openqa.selenium.remote.ErrorHandler.rebuildServerError(ErrorHandler.java:270)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:118)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:399)
	at org.openqa.selenium.By$ById.findElement(By.java:215)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:102)
	at com.sun.proxy.$Proxy1.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:185)
	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16:55:52.258 WARN - Exception: java.lang.String cannot be cast to java.lang.Number
```

The code I'm using is:

```php
<?php
require '__init__.php';

$capabilities = array(\WebDriverCapabilityType::BROWSER_NAME => 'firefox');
$webDriver = RemoteWebDriver::create('http://localhost:4444/wd/hub', $capabilities);

$webDriver->get('http://www.drugs.com/');

$search = $webDriver->findElement(WebDriverBy::id('livesearch-main'));
$search->click();

$webDriver->getKeyboard()->sendKeys('test');
```

I'm using a cloned copy of this repo (updated today) and Selenium:

```
16:54:31.998 INFO - Launching a standalone Selenium Server
16:54:32.027 INFO - Java: Oracle Corporation 25.20-b23
16:54:32.027 INFO - OS: Mac OS X 10.10.4 x86_64
16:54:32.037 INFO - v2.46.0, with Core v2.46.0. Built from revision 87c69e2
```

**Comment by AlexMiroshnikov** [comment]
Looks like a Mac or Java b23 version specific issue. I've just tested on Debian 7 with the same version of the repo and Selenium and it works completely fine:
```
17:26:32.228 INFO - Launching a standalone Selenium Server
17:26:32.269 INFO - Java: Oracle Corporation 25.25-b02
17:26:32.269 INFO - OS: Linux 3.2.0-4-amd64 amd64
17:26:32.281 INFO - v2.46.0, with Core v2.46.0. Built from revision 87c69e2
...
17:26:41.920 INFO - Executing: [new session: Capabilities [{browserName=htmlunit}]])
17:26:41.937 INFO - Creating a new session for Capabilities [{browserName=htmlunit}]
17:26:43.267 INFO - Done: [new session: Capabilities [{browserName=htmlunit}]]
17:26:43.303 INFO - Executing: [new session: Capabilities [{browserName=firefox}]])
17:26:43.305 INFO - Creating a new session for Capabilities [{browserName=firefox}]
17:26:46.566 INFO - Done: [new session: Capabilities [{browserName=firefox}]]
17:26:46.572 INFO - Executing: [get: http://www.drugs.com/])
17:26:50.828 INFO - Done: [get: http://www.drugs.com/]
17:26:50.832 INFO - Executing: [find element: By.id: livesearch-main])
17:26:50.918 INFO - Done: [find element: By.id: livesearch-main]
17:26:50.925 INFO - Executing: [click: 0 [[FirefoxDriver: firefox on LINUX (c0aa96a4-8f03-477f-87c3-c197479cc53b)] -> id: livesearch-main]])
17:26:51.035 INFO - Done: [click: 0 [[FirefoxDriver: firefox on LINUX (c0aa96a4-8f03-477f-87c3-c197479cc53b)] -> id: livesearch-main]]
17:26:51.039 INFO - Executing: [send keys to active: [test]])
17:26:51.166 INFO - Done: [send keys to active: [test]]
17:26:51.169 INFO - Executing: [delete session: d74a50ba-8846-4b30-a519-c9f4e413829f])
17:26:51.173 INFO - Done: [delete session: d74a50ba-8846-4b30-a519-c9f4e413829f]
```

**Comment by NoodlesNZ** [comment]
I also see it happening on Windows with 25.51-b03.

What's weird is it only happens on some sites.

**Comment by NoodlesNZ** [comment]
Seems to be related to our Javascript error handler/exceptionWrapper and Selenium not playing nice together:

```
function exceptionWrapper(fn)
	{
		if(!fn.apply) {
			return fn;
		}

		return function()
		{
			try {
				return fn.apply(this, arguments);
			}
			catch(ex) {
				// Store error data in local var
				_exception = {
					message: ex.message || '',
					file: ex.fileName || '',
					line: ex.lineNumber || '',
					column: ex.columnNumber || '',
					stack: ex.stack || ''
				};

				// Throw exception for error handler
				throw(ex);
			}
		};
	}
```

If I remove that then it works correctly. I don't think this is a php-webdriver issue.
