### ISSUE TITLE
PHP-WebDriver with MacOS Sierra 10.12 doesn’t work methods with waiting for condition, like waitForElement… and waitForElementNot...

### ISSUE THREAD

**Issue by sakharovmaksim** [facebook/php-webdriver#328]
OS:
MacOS Sierra 10.12
Selenium Version:

2.53.1, 3.0.0-beta3
Facebook php-adapter

Browser:
Chrome

When i upgrade to macOS Sierra, i faced a problem that all WebDrivers methods with waiting until a condition, like $_webDriver->wait($timeout)->until(WebDriverExpectedCondition::presenceOfElementLocated($selector) doesn’t work correctly.

The problem is, if target selector is not visible or present now, WebDriver not trying to repeat check this selector again and again. WebDriver trying once and after timeout, just throws an Exception (NoSuchElementException).

The El Capitan (10.11) didn't have a problem.

Code:
return self::$_webDriver->wait($timeout)->until(			WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::cssSelector((string) $cssSelector)),
$message
);

Log:
12:58:13.038 INFO - Executing: [find element: By.cssSelector: .l-badge_new_wrapper #uBadgeBlock #uName])
12:58:24.008 WARN - Exception thrown
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":" .l-badge_new_wrapper #uBadgeBlock #uName"}
(Session info: chrome=53.0.2785.116)
(Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.0.0-beta3', revision: 'c7b525d', time: '2016-09-01 14:57:03 -0700'
System info: host: 'Sakharov-MacBook-Pro.local', ip: '10.10.64.11', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_74'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=true, networkConnectionEnabled=false, chrome={chromedriverVersion=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6), userDataDir=/var/folders/lj/4bqf7t556k964jh071mxq8040000gn/T/.org.chromium.Chromium.Qfcl87}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=true, version=53.0.2785.116, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 4fb3f72ae02f3a6b4833cc3a261b21fe
*** Element info: {Using=css selector, value= .l-badge_new_wrapper #uBadgeBlock #uName}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:631)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:369)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:466)
at org.openqa.selenium.By$ByCssSelector.findElement(By.java:430)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:361)
at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
at com.sun.proxy.$Proxy3.findElement(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:187)
at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:33)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

-->

Browser Version:

53.0.2785.116

Expected Behavior -

WebDriver not trying to repeat check selector’s condition again and again.

Actual Behavior -

WebDriver trying once and after timeout, just throws an Exception (NoSuchElementException).

Steps to reproduce -

Try execute waitForElement... on element, witch don’t visible or present in current time, but it will soon be seen or present.
WebDriver trying once check this element, and throws Exception.

Please, fix this problem! I couldn't use WebDriver with MacOS Sierra.

**Comment by gustavomanolo** [comment]
HI, i've MacOS Sierra too and i'm having a similar problem. I posted in #332 , do you think is the same?

**Comment by sakharovmaksim** [comment]
The problem fix by change etc/hosts file, like:

127.0.0.1       localhost Sakharov-MacBook-Pro.local
::1             localhost Sakharov-MacBook-Pro.local

**Comment by hariesnurikhwan** [comment]
@sakharovmaksim do you mind to share your findings on how to fix the issue? It works for me too but I'm a bit curious.

**Comment by sakharovmaksim** [comment]
I think, that MacOS Sierra has a problem with DNS…
