### ISSUE TITLE
WebDriverCurlException for webdriver with FF

### ISSUE THREAD

**Issue by JeroenSteen** [facebook/php-webdriver#441]
### Trying to achieve (Expected behavior)
I want to use the newest Selenium with facebook/php-webdriver.

### WebDriverCurlException (Actual behavior)
But I get this error in the browser targetting my PHP file:
`Uncaught exception 'Facebook\WebDriver\Exception\WebDriverCurlException' with message 'Curl error thrown for http POST to /session`. How can I fix this behavior?

I runned Selenium with the Geckodriver 16.1 provided, with these command:

    java -Dwebdriver.gecko.driver="/opt/bin/geckodriver" -jar  selenium-server-standalone-3.4.0.jar

I also installed Xvfb. This is my PHP code:

```php
namespace Facebook\WebDriver;

include("vendor/autoload.php");

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

$host = "http://localhost:4444/wd/hub";
$profile = new Firefox\FirefoxProfile();
$capabilities = DesiredCapabilities::firefox();
$capabilities->setCapability(Firefox\FirefoxDriver::PROFILE, $profile);
$capabilities->setCapability('marionette', true);
$driver = RemoteWebDriver::create($host, $capabilities);

$driver->get("http://www.google.nl");
$driver->manage()->timeouts()->implicitlyWait = 10;
```

### Details

* Php-webdriver version: ^1.1
* PHP version: PHP 5.6.30
* Selenium server version: 3.4
* Operating system: CentOS 7
* Browser used + version: Firefox 52.1

**Comment by OndraM** [comment]
@JeroenSteen Hi, isn't there anything more shown in the error? Also is there any difference when 
a) not setting the firefox profile 
b) not setting the marionette capability? (BTW is not necessary, this is already true by default in Selenium 3.x)

Thanks!

**Comment by JeroenSteen** [comment]
I also see `GDK_BACKEND does not match available displays` in the terminal (but I have Xvfb), this is the output in the terminal:

```
13:56:07.070 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
13:56:07.071 INFO - Launching a standalone Selenium Server
2017-05-03 13:56:07.090:INFO::main: Logging initialized @327ms to org.seleniumhq.jetty9.util.log.StdErrLog
13:56:07.157 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
13:56:07.158 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
13:56:07.158 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:56:07.158 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
13:56:07.158 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:56:07.158 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
13:56:07.159 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
2017-05-03 13:56:07.213:INFO:osjs.Server:main: jetty-9.4.3.v20170317
2017-05-03 13:56:07.262:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@475530b9{/,null,AVAILABLE}
2017-05-03 13:56:07.283:INFO:osjs.AbstractConnector:main: Started ServerConnector@148eb56c{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-05-03 13:56:07.284:INFO:osjs.Server:main: Started @521ms
13:56:07.284 INFO - Selenium Server is up and running
13:56:10.346 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
13:56:10.377 INFO - Executing: [new session: Capabilities [{marionette=true, browserName=firefox, platform=ANY, firefox_profile=UEsDBBQAAAAAAAV/o0oAAAAAAAAAAAAAAAAHAAAAdXNlci5qc1BLAQIUAxQAAAAAAAV/o0oAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAC2gQAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAACUAAAAAAA==}]])
13:56:10.402 INFO - Creating a new session for Capabilities [{marionette=true, browserName=firefox, platform=ANY, firefox_profile=UEsDBBQAAAAAAAV/o0oAAAAAAAAAAAAAAAAHAAAAdXNlci5qc1BLAQIUAxQAAAAAAAV/o0oAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAC2gQAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAACUAAAAAAA==}]
1493819770784   geckodriver     INFO    Listening on 127.0.0.1:27627
1493819771046   geckodriver::marionette INFO    Starting browser /usr/bin/firefox with args ["-marionette"]
Error: GDK_BACKEND does not match available displays
13:57:11.793 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'h2446783.stratoserver.net', ip: '85.214.60.202', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-042stab120.20', java.version: '1.8.0_77'
Driver info: driver.version: unknown
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:131)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:190)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'h2446783.stratoserver.net', ip: '85.214.60.202', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-042stab120.20', java.version: '1.8.0_77'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:89)
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:63)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:81)
        ... 9 more
Caused by: org.openqa.selenium.WebDriverException: connection refused
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'h2446783.stratoserver.net', ip: '85.214.60.202', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-042stab120.20', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4fa94d - backtrace::backtrace::trace::h45ace4059cd74233
   1:           0x4fae32 - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
   2:           0x4349d9 - webdriver::error::WebDriverError::new::h449345a591a119fd
   3:           0x43f6b0 - geckodriver::marionette::MarionetteHandler::create_connection::h53f581202e4008b4
   4:           0x442839 - <geckodriver::marionette::MarionetteHandler as webdriver::server::WebDriverHandler<geckodriver::marionette::GeckoExtensionRoute>>::handle_command::hd89c5efbeb4c7cd5
   5:           0x434e94 - webdriver::server::start::{{closure}}::h5e71183f67357de6
   6:           0x408627 - std::panicking::try::do_call::h8c30e6af4c7f85af
   7:           0x5b77fa - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libpanic_unwind/lib.rs:98
   8:           0x416e57 - <F as alloc::boxed::FnBox<A>>::call_box::h3f273b2445d78deb
   9:           0x5b0014 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc/boxed.rs:624
                         - std::sys_common::thread::start_thread
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys/unix/thread.rs:84
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
        ... 14 more
13:57:11.864 WARN - Exception: connection refused
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'h2446783.stratoserver.net', ip: '85.214.60.202', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-042stab120.20', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4fa94d - backtrace::backtrace::trace::h45ace4059cd74233
   1:           0x4fae32 - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
   2:           0x4349d9 - webdriver::error::WebDriverError::new::h449345a591a119fd
   3:           0x43f6b0 - geckodriver::marionette::MarionetteHandler::create_connection::h53f581202e4008b4
   4:           0x442839 - <geckodriver::marionette::MarionetteHandler as webdriver::server::WebDriverHandler<geckodriver::marionette::GeckoExtensionRoute>>::handle_command::hd89c5efbeb4c7cd5
   5:           0x434e94 - webdriver::server::start::{{closure}}::h5e71183f67357de6
   6:           0x408627 - std::panicking::try::do_call::h8c30e6af4c7f85af
   7:           0x5b77fa - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libpanic_unwind/lib.rs:98
   8:           0x416e57 - <F as alloc::boxed::FnBox<A>>::call_box::h3f273b2445d78deb
   9:           0x5b0014 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/liballoc/boxed.rs:624
                         - std::sys_common::thread::start_thread
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-musl-linux/build/src/libstd/sys/unix/thread.rs:84
```

**Comment by bluejamesbond** [comment]
@JeroenSteen Any updates on this issue? I am also stuck with this error

**Comment by cryptton2004** [comment]
I run my tests on windows so I have no way of testing this at the moment, but can you try this before running the selenium server?
`export DISPLAY=":1" && java -Dwebdriver.gecko.driver="/opt/bin/geckodriver" -jar  selenium-server-standalone-3.4.0.jar`
where 'DISPLAY=":X" is the display port number you have started xvfb with.

**Comment by addrians** [comment]
Running on a similar setup, but a remote selenium server, I have a similar issue that is caused by the remote response of the session creation. Basically, the json has the 'session_id' key under the 'value' key instead of the root object.

Adding the following line to [HttpCommandExecutor.php](https://github.com/facebook/php-webdriver/blob/community/lib/Remote/HttpCommandExecutor.php#L312)
`if(!isset($results['sessionId']) and isset($results['value']['sessionId'])) $results['sessionId'] = $results['value']['sessionId'];`
fixes the issue.

**Comment by OndraM** [comment]
Part of #469 .
