### ISSUE TITLE
There is something wrong with using chrome browser

### ISSUE THREAD

**Issue by tangtingting** [facebook/php-webdriver#450]
I am a newer,I use chrome for testing ,I consult wiki for help,but I have some problems.
 
 define capabilities:
 $host = 'http://localhost:4444/wd/hub'; // this is the default
  $capabilities = DesiredCapabilities::htmlUnitWithJS();
  {
    // For Chrome
    $options = new ChromeOptions();
    $prefs = array('download.default_directory' => 'c:/temp');
    $options->setExperimentalOption('prefs', $prefs);
    $capabilities = DesiredCapabilities::chrome(); 
    $capabilities->setCapability(ChromeOptions::CAPABILITY, $options);
  }
  $driver = RemoteWebDriver::create($host, $capabilities, 5000);

my chrome version: 58.0.3029.110
my excute selenium ：java -jar selenium-server-standalone-2.40.0.jar -Dwebdriver.chrome.driver=D:\software\ChromeDriver2.30\chromedriver.exe

**ERROR LOG:**
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\WebDriverException: JSON decoding of remote response failed.
Error code: 4
The response: ''
 in D:\test\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php:326
Stack trace:
#0 D:\test\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(547): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#1 D:\test\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(195): Facebook\WebDriver\Remote\RemoteWebDriver->execute('get', Array)
#2 D:\test\chrome.php(19): Facebook\WebDriver\Remote\RemoteWebDriver->get('http://www.baid...')
#3 {main}
  thrown in D:\test\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php on line 326

**Comment by tangtingting** [comment]
my php version is : 7.1.6
When I  change a lower version 5.6.30 ,the problem abrove just like solved.
