### ISSUE TITLE
Unknown option: -Dwebdriver.chrome.driver

### ISSUE THREAD

**Issue by YuK1Game** [facebook/php-webdriver#453]
Windows 7
```
java -jar ./drivers/selenium-server-standalone-3.4.0.jar -Dwebdriver.chrome.driver="./drivers/"
```
Error Message
```
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -Dwebdriver.chrome.driver="./drivers/"
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
        at org.openqa.grid.selenium.GridLauncherV3$1.setConfiguration(GridLauncherV3.java:227)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:155)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:75)
```

How do I specify the driver's path?

thanks.

**Comment by OndraM** [comment]
Hi,
1. The -D... must *precede* the -jar parameter
2. The path must AFAIK be to the binary itself (like ./drivers/chromedriver.exe), not just the path :)
