### ISSUE TITLE
Obscure error message

### ISSUE THREAD

**Issue by salarmehr** [facebook/php-webdriver#478]
```
Facebook\WebDriver\Exception\StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 10.0.15063 x86_64)
```

This error message says something missing in the page but why it is such cryptic. No reference to the object itself. Is it possible to improve it make it more informative?

**Comment by paulbriton** [comment]
Try to update to [latest chromedriver](https://chromedriver.storage.googleapis.com/index.html?path=2.32/), it should work.

**Comment by OndraM** [comment]
Hi @salarmehr , for more explanation of this exception, see comprehensive description on Selenium project page: http://www.seleniumhq.org/exceptions/stale_element_reference.jsp

What exactly happened could be seen  from the stacktrace, which should by provided to you by the testing framework you use (like PHPUnit, Codeception etc.). If you happened to not use any, you have to catch the exception and print the stacktrace by yourselves, eg. like this: http://php.net/manual/en/exception.gettraceasstring.php

If you think is is an error, please fill full bug report here on GitHub, according to the template provided when you create a new issue.

Thank you :)

**Comment by salarmehr** [comment]
@OndraM Thanks for your response. Do you mean its not possible to improve the error wording as it's from Selenium core? I added the trace stack yet it's not clear what is missing in the page. 

```
#0 C:\http\dusk\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(10, 'stale element r...', Array)
#1 C:\http\dusk\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(535): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 C:\http\dusk\vendor\facebook\webdriver\lib\Remote\RemoteExecuteMethod.php(40): Facebook\WebDriver\Remote\RemoteWebDriver->execute('getElementText', Array)
#3 C:\http\dusk\vendor\facebook\webdriver\lib\Remote\RemoteWebElement.php(273): Facebook\WebDriver\Remote\RemoteExecuteMethod->execute('getElementText', Array)
#4 C:\http\dusk\vendor\laravel\dusk\src\Concerns\MakesAssertions.php(238): Facebook\WebDriver\Remote\RemoteWebElement->getText()
#5 C:\http\dusk\vendor\laravel\dusk\src\Concerns\MakesAssertions.php(210): Laravel\Dusk\Browser->assertSeeIn('', 'Basic')
#6 C:\http\dusk\tests\Browser\SignupTest.php(27): Laravel\Dusk\Browser->assertSee('Basic')
#7 C:\http\dusk\vendor\laravel\dusk\src\TestCase.php(91): Tests\Browser\SignupTest->Tests\Browser\{closure}(Object(Laravel\Dusk\Browser))
#8 C:\http\dusk\tests\Browser\SignupTest.php(40): Laravel\Dusk\TestCase->browse(Object(Closure))
#9 [internal function]: Tests\Browser\SignupTest->testPlans()
#10 C:\http\dusk\vendor\phpunit\phpunit\src\Framework\TestCase.php(1054): ReflectionMethod->invokeArgs(Object(Tests\Browser\SignupTest), Array)
#11 C:\http\dusk\vendor\phpunit\phpunit\src\Framework\TestCase.php(905): PHPUnit_Framework_TestCase->runTest()
#12 C:\http\dusk\vendor\phpunit\phpunit\src\Framework\TestResult.php(686): PHPUnit_Framework_TestCase->runBare()
#13 C:\http\dusk\vendor\phpunit\phpunit\src\Framework\TestCase.php(860): PHPUnit_Framework_TestResult->run(Object(Tests\Browser\SignupTest))
#14 C:\http\dusk\vendor\phpunit\phpunit\src\Framework\TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#15 C:\http\dusk\vendor\phpunit\phpunit\src\Framework\TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#16 C:\http\dusk\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(517): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#17 C:\http\dusk\vendor\phpunit\phpunit\src\TextUI\Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array, true)
#18 C:\http\dusk\vendor\phpunit\phpunit\src\TextUI\Command.php(116): PHPUnit_TextUI_Command->run(Array, true)
#19 C:\http\dusk\vendor\phpunit\phpunit\phpunit(52): PHPUnit_TextUI_Command::main()
#20 {main}.                                                                  2 / 2 (100%)

```

**Comment by salarmehr** [comment]
@paulbriton Interestingly after your comment another version is released.
