### ISSUE TITLE
example.php not working

### ISSUE THREAD

**Issue by flik** [facebook/php-webdriver#532]
### What are you trying to achieve? (Expected behavior)
executing example.php file

### What do you get instead? (Actual behavior)
```
 php fb.php
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\SessionNotCreatedException: Unable to create new service: GeckoDriverService
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
System info: host: 'Asfaq-MoveOn', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: unknown in D:\ProjectMega\mweb\testCaces\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:154
Stack trace:
#0 D:\ProjectMega\mweb\testCaces\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(33, 'Unable to creat...', Ar
ray)
#1 D:\ProjectMega\mweb\testCaces\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDrive
rCommand))
#2 D:\ProjectMega\mweb\testCaces\tests\api\fb.php(10): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object in D:\ProjectMega\mweb\testCaces\vendor\facebook\webdriver
\lib\Exception\WebDriverException.php on line 154

Fatal error: Uncaught Facebook\WebDriver\Exception\SessionNotCreatedException: Unable to create new service: GeckoDriverService
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
System info: host: 'Asfaq-MoveOn', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: unknown in D:\ProjectMega\mweb\testCaces\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:154
Stack trace:
#0 D:\ProjectMega\mweb\testCaces\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(33, 'Unable to creat...', Ar
ray)
#1 D:\ProjectMega\mweb\testCaces\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDrive
rCommand))
#2 D:\ProjectMega\mweb\testCaces\tests\api\fb.php(10): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object in D:\ProjectMega\mweb\testCaces\vendor\facebook\webdriver
\lib\Exception\WebDriverException.php on line 154


```
### How could the issue be reproduced? (Steps to reproduce)
create file fb.php and paste all example.php code in it. then run

```php
<?php
// An example of using php-webdriver.
namespace Facebook\WebDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
require_once('../../vendor/autoload.php');

// start Firefox with 5 second timeout
$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::firefox();
$driver = RemoteWebDriver::create($host, $capabilities, 5000);
// navigate to 'http://www.seleniumhq.org/'
$driver->get('http://www.seleniumhq.org/');
// adding cookie
$driver->manage()->deleteAllCookies();
$cookie = new Cookie('cookie_name', 'cookie_value');
$driver->manage()->addCookie($cookie);
$cookies = $driver->manage()->getCookies();
print_r($cookies);
// click the link 'About'
$link = $driver->findElement(
    WebDriverBy::id('menu_about')
);
$link->click();
// wait until the page is loaded
$driver->wait()->until(
    WebDriverExpectedCondition::titleContains('About')
);
// print the title of the current page
echo "The title is '" . $driver->getTitle() . "'\n";
// print the URI of the current page
echo "The current URI is '" . $driver->getCurrentURL() . "'\n";
// write 'php' in the search box
$driver->findElement(WebDriverBy::id('q'))
    ->sendKeys('php');
// submit the form
$driver->findElement(WebDriverBy::id('submit'))
    ->click(); // submit() does not work in Selenium 3 because of bug https://github.com/SeleniumHQ/selenium/issues/3398
// wait at most 10 seconds until at least one result is shown
$driver->wait(10)->until(
    WebDriverExpectedCondition::presenceOfAllElementsLocatedBy(
        WebDriverBy::className('gsc-result')
    )
);
// close the Firefox
$driver->quit();
```

### Details

* Php-webdriver version:  https://github.com/facebook/php-webdriver
* PHP version: 7.x
* Selenium server version: selenium-server-standalone-3.9.1.jar
* Operating system: Windows
* Browser used + version: Firfox

**Comment by OndraM** [comment]
Hi, this is related to #469 .

I suggest using Selenium server 3.8.1 with enablePassThrough set to false, as noted in readme: https://github.com/facebook/php-webdriver#getting-started

**Comment by x558li** [comment]
selenium-server-standalone-3.8.1.jar is no longer available. The current version is 3.141.59 and -enablePassThrough is also not available now. In this case, is there any solution to this issue? @OndraM

**Comment by halfer** [comment]
I am getting this Symfony/Panther, but only with ParaTest, and when using multiple processes. Using one process does not trigger the problem (though it makes ParaTest redundant).
