### ISSUE TITLE
example.php is still not working

### ISSUE THREAD

**Issue by flik** [facebook/php-webdriver#538]
### What are you trying to achieve? (Expected behavior)
running example.php

### What do you get instead? (Actual behavior)

```bash

feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver
$ git clone https://github.com/facebook/php-webdriver.git
Cloning into 'php-webdriver'...
remote: Counting objects: 6557, done.
remote: Total 6557 (delta 0), reused 0 (delta 0), pack-reused 6557
Receiving objects: 100% (6557/6557), 2.25 MiB | 118.00 KiB/s, done.
Resolving deltas: 100% (4921/4921), done.
Checking connectivity... done.

feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver
$ ls
1 - Copy.php   example.php  php-webdriver/                        tests/
composer.json  LICENSE      README.md                             vendor/
composer.lock  phpunit.xml  selenium-server-standalone-3.9.1.jar

feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver
$ cd php-webdriver/

feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver/php-webdriver (community)
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 55 installs, 0 updates, 0 removals
  - Installing symfony/yaml (v3.4.6): Loading from cache
  - Installing symfony/stopwatch (v3.4.6): Downloading (0%)
Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.7.0): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.4.6): Loading from cache
  - Installing symfony/console (v3.4.6): Loading from cache
  - Installing symfony/filesystem (v3.4.6): Downloading (100%)
  - Installing symfony/config (v3.4.6): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.0): Downloading (100%)
  - Installing php-coveralls/php-coveralls (v2.0.0): Downloading (100%)
  - Installing jakub-onderka/php-parallel-lint (v0.9.2): Downloading (100%)
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/diff (1.4.3): Downloading (100%)
  - Installing symfony/process (v3.4.6): Loading from cache
  - Installing symfony/polyfill-php72 (v1.7.0): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.11): Downloading (100%)
  - Installing symfony/polyfill-php70 (v1.7.0): Downloading (100%)
  - Installing symfony/options-resolver (v3.4.6): Downloading (100%)
  - Installing symfony/finder (v3.4.6): Loading from cache
  - Installing symfony/event-dispatcher (v3.4.6): Loading from cache
  - Installing php-cs-fixer/diff (v1.3.0): Downloading (100%)
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)
  - Installing doctrine/annotations (v1.4.0): Downloading (100%)
  - Installing composer/semver (1.4.2): Downloading (100%)
  - Installing friendsofphp/php-cs-fixer (v2.10.4): Downloading (100%)
  - Installing squizlabs/php_codesniffer (2.9.1): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing php-mock/php-mock (1.0.1): Downloading (100%)
  - Installing php-mock/php-mock-integration (1.0.0): Downloading (100%)
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/recursion-context (2.0.0): Downloading (100%)
  - Installing sebastian/object-enumerator (2.0.1): Downloading (100%)
  - Installing sebastian/global-state (1.1.1): Downloading (100%)
  - Installing sebastian/exporter (2.0.0): Downloading (100%)
  - Installing sebastian/environment (2.0.0): Downloading (100%)
  - Installing sebastian/comparator (1.2.4): Downloading (100%)
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/phpunit-mock-objects (3.4.4): Downloading (100%)
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (4.0.8): Downloading (100%)
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.7.5): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (5.7.27): Downloading (100%)
  - Installing php-mock/php-mock-phpunit (1.1.2): Downloading (0%)
Downloading (100%)
  - Installing symfony/var-dumper (v3.4.6): Downloading (100%)
symfony/console suggests installing symfony/lock ()
php-coveralls/php-coveralls suggests installing symfony/http-kernel (Allows Symfony integration)
jakub-onderka/php-parallel-lint suggests installing jakub-onderka/php-console-highlighter (Highlight syntax in code snippet)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
php-mock/php-mock suggests installing php-mock/php-mock-mockery (Allows using PHPMockery for Mockery integration)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
symfony/var-dumper suggests installing ext-symfony_debug ()
Writing lock file
Generating autoload files

feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver/php-webdriver (community)
$ ls
CHANGELOG.md        composer.lock    ISSUE_TEMPLATE.md  logs/             README.md
CODE_OF_CONDUCT.md  CONTRIBUTING.md  lib/               phpstan.neon      tests/
composer.json       example.php      LICENCE.md         phpunit.xml.dist  vendor/

feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver/php-webdriver (community)
$ php example.php
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for h
ttp POST to /session with params: {"desiredCapabilities":{"browserName":"firefox","platform":"ANY","fir
efox_profile":"UEsDBBQAAAAAAFtFaUzf9RXUMgAAADIAAAAHAAAAdXNlci5qc3VzZXJfcHJlZigicmVhZGVyLnBhcnNlLW9uLWxv
YWQuZW5hYmxlZCIsIGZhbHNlKTsKUEsBAhQDFAAAAAAAW0VpTN\/1FdQyAAAAMgAAAAcAAAAAAAAAAAAAALaBAAAAAHVzZXIuanNQSw
UGAAAAAAEAAQA1AAAAVwAAAAAA"}}

Failed to connect to localhost port 4444: Connection refused in D:\xampp\htdocs\php-webdriver\php-webdr
iver\lib\Remote\HttpCommandExecutor.php:292
Stack trace:
#0 D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\
Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#1 D:\xampp\htdocs\php-webdriver\php-webdriver\example.php(14): Facebook\WebDriver\Remote\RemoteWebDriv
er::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 5000)
#2 {main}
  thrown in D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\HttpCommandExecutor.php on line 292

Fatal error: Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http P
OST to /session with params: {"desiredCapabilities":{"browserName":"firefox","platform":"ANY","firefox_
profile":"UEsDBBQAAAAAAFtFaUzf9RXUMgAAADIAAAAHAAAAdXNlci5qc3VzZXJfcHJlZigicmVhZGVyLnBhcnNlLW9uLWxvYWQuZ
W5hYmxlZCIsIGZhbHNlKTsKUEsBAhQDFAAAAAAAW0VpTN\/1FdQyAAAAMgAAAAcAAAAAAAAAAAAAALaBAAAAAHVzZXIuanNQSwUGAAA
AAAEAAQA1AAAAVwAAAAAA"}}

Failed to connect to localhost port 4444: Connection refused in D:\xampp\htdocs\php-webdriver\php-webdr
iver\lib\Remote\HttpCommandExecutor.php:292
Stack trace:
#0 D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\
Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#1 D:\xampp\htdocs\php-webdriver\php-webdriver\example.php(14): Facebook\WebDriver\Remote\RemoteWebDriv
er::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 5000)
#2 {main}
  thrown in D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\HttpCommandExecutor.php on line 292

feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver/php-webdriver (community)

```

### How could the issue be reproduced? (Steps to reproduce)

```php
php example.php

<?php
// An example of using php-webdriver.

namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

require_once('vendor/autoload.php');

// start Firefox with 5 second timeout
$host = 'http://localhost:4444/wd/hub'; // this is the default
$capabilities = DesiredCapabilities::firefox();
$driver = RemoteWebDriver::create($host, $capabilities, 5000);

// navigate to 'http://www.seleniumhq.org/'
$driver->get('http://www.seleniumhq.org/');

// adding cookie
$driver->manage()->deleteAllCookies();

$cookie = new Cookie('cookie_name', 'cookie_value');
$driver->manage()->addCookie($cookie);

$cookies = $driver->manage()->getCookies();
print_r($cookies);

// click the link 'About'
$link = $driver->findElement(
    WebDriverBy::id('menu_about')
);
$link->click();

// wait until the page is loaded
$driver->wait()->until(
    WebDriverExpectedCondition::titleContains('About')
);

// print the title of the current page
echo "The title is '" . $driver->getTitle() . "'\n";

// print the URI of the current page
echo "The current URI is '" . $driver->getCurrentURL() . "'\n";

// write 'php' in the search box
$driver->findElement(WebDriverBy::id('q'))
    ->sendKeys('php');

// submit the form
$driver->findElement(WebDriverBy::id('submit'))
    ->click(); // submit() does not work in Selenium 3 because of bug https://github.com/SeleniumHQ/selenium/issues/3398

// wait at most 10 seconds until at least one result is shown
$driver->wait(10)->until(
    WebDriverExpectedCondition::presenceOfAllElementsLocatedBy(
        WebDriverBy::className('gsc-result')
    )
);

// close the Firefox
$driver->quit();

```

### Details

* Php-webdriver version:  latest https://github.com/facebook/php-webdriver.git
* PHP version: 7.x
* Selenium server version: selenium-server-standalone-3.9.1
* Operating system: Windows 8.1
* Browser used + version:  Firefox / crome

**Comment by OndraM** [comment]
Hi @flik .

First of all, please follow steps in README, especially the install part: https://github.com/facebook/php-webdriver#installation
Ie. you don't need to clone this repository - php-webdriver should be added to your project with selenium tests using `composer require facebook/webdriver`.

As there are now issues starting Firefox, I updated the example to use Chrome - see it [here](https://github.com/facebook/php-webdriver/blob/community/example.php).

Also from your report above, I don't see you started selenium server - please refer to [Getting started](https://github.com/facebook/php-webdriver#getting-started)  section of readme. This may be the reason why you got the exception, which states Selenium is not available on port 4444 (`Failed to connect to localhost port 4444: Connection refused`).

**Comment by flik** [comment]
Hi dear,
Selenium server is already running. I can not add here screen short.
here is the output:
feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver/php-webdriver (community)
$ composer require facebook/webdriver
Using version ^1.5 for facebook/webdriver
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files

here i the output of example.php: 
feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver/php-webdriver (community)
$ php example.php
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\SessionNotCreatedExcepti
on: Unable to create new service: GeckoDriverService
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.40
3Z'
System info: host: 'adminxA', ip: '192.168.56.1', os.name: 'Windows 8', os.arch:
 'amd64', os.version: '6.2', java.version: '1.8.0_161'
Driver info: driver.version: unknown in D:\xampp\htdocs\php-webdriver\php-webdri
ver\lib\Exception\WebDriverException.php:154
Stack trace:
#0 D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\HttpCommandExecutor.ph
p(326): Facebook\WebDriver\Exception\WebDriverException::throwException(33, 'Una
ble to creat...', Array)
#1 D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\RemoteWebDriver.php(12
6): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDr
iver\Remote\WebDriverCommand))
#2 D:\xampp\htdocs\php-webdriver\php-webdriver\example.php(14): Facebook\WebDriv
er\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDrive
r\Remote\Desired in D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Exception\We
bDriverException.php on line 154

Fatal error: Uncaught Facebook\WebDriver\Exception\SessionNotCreatedException: U
nable to create new service: GeckoDriverService
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.40
3Z'
System info: host: 'adminxA', ip: '192.168.56.1', os.name: 'Windows 8', os.arch:
 'amd64', os.version: '6.2', java.version: '1.8.0_161'
Driver info: driver.version: unknown in D:\xampp\htdocs\php-webdriver\php-webdri
ver\lib\Exception\WebDriverException.php:154
Stack trace:
#0 D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\HttpCommandExecutor.ph
p(326): Facebook\WebDriver\Exception\WebDriverException::throwException(33, 'Una
ble to creat...', Array)
#1 D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\RemoteWebDriver.php(12
6): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDr
iver\Remote\WebDriverCommand))
#2 D:\xampp\htdocs\php-webdriver\php-webdriver\example.php(14): Facebook\WebDriv
er\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDrive
r\Remote\Desired in D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Exception\We
bDriverException.php on line 154

here is selenium server:
$ java -jar selenium-server-standalone-3.9.1.jar
06:45:45.849 INFO - Selenium build info: version: '3.9.1', revision: '63f7b50'
06:45:45.849 INFO - Launching a standalone Selenium Server on port 4444
2018-03-10 06:45:45.932:INFO::main: Logging initialized @359ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-03-10 06:45:46.047:INFO:osjs.Server:main: jetty-9.4.7.v20170914, build timestamp: 2017-11-22T02:27:37+05:00, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-03-10 06:45:46.090:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@2b2948e2{/,null,STARTING} has uncovered http methods for path: /
2018-03-10 06:45:46.096:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@2b2948e2{/,null,AVAILABLE}
2018-03-10 06:45:46.566:INFO:osjs.AbstractConnector:main: Started ServerConnector@53f65459{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2018-03-10 06:45:46.567:INFO:osjs.Server:main: Started @993ms
06:45:46.567 INFO - Selenium Server is up and running on port 4444
2018-03-10 06:46:09.593:INFO:osjshC.ROOT:qtp654845766-13: org.openqa.selenium.remote.server.WebDriverServlet-d8355a8: Initialising WebDriverServlet
06:46:09.661 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@4ee25198
06:46:09.665 INFO - /session: Executing POST on /session (handler: BeginSession)
06:46:09.741 INFO - Capabilities are: Capabilities {browserName: firefox, firefox_profile: UEsDBBQAAAAAAMQ1akzf9RXUMgA...}
06:46:09.743 INFO - Capabilities {browserName: firefox, firefox_profile: UEsDBBQAAAAAAMQ1akzf9RXUMgA...} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)

**Comment by flik** [comment]
I modified the host in example to 0.0.0.0:4444 as per selenium and getting the output:

```
feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver/php-webdriver (community)
$ php example.php
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for h
ttp POST to /session with params: {"desiredCapabilities":{"browserName":"firefox","platform":"ANY","fir
efox_profile":"UEsDBBQAAAAAALw2akzf9RXUMgAAADIAAAAHAAAAdXNlci5qc3VzZXJfcHJlZigicmVhZGVyLnBhcnNlLW9uLWxv
YWQuZW5hYmxlZCIsIGZhbHNlKTsKUEsBAhQDFAAAAAAAvDZqTN\/1FdQyAAAAMgAAAAcAAAAAAAAAAAAAALaBAAAAAHVzZXIuanNQSw
UGAAAAAAEAAQA1AAAAVwAAAAAA"}}

Failed to connect to 0.0.0.0 port 4444: Address not available in D:\xampp\htdocs\php-webdriver\php-webd
river\lib\Remote\HttpCommandExecutor.php:292
Stack trace:
#0 D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\
Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#1 D:\xampp\htdocs\php-webdriver\php-webdriver\example.php(14): Facebook\WebDriver\Remote\RemoteWebDriv
er::create('http://0.0.0.0:...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 5000)
#2 {main}
  thrown in D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\HttpCommandExecutor.php on line 292

Fatal error: Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http P
OST to /session with params: {"desiredCapabilities":{"browserName":"firefox","platform":"ANY","firefox_
profile":"UEsDBBQAAAAAALw2akzf9RXUMgAAADIAAAAHAAAAdXNlci5qc3VzZXJfcHJlZigicmVhZGVyLnBhcnNlLW9uLWxvYWQuZ
W5hYmxlZCIsIGZhbHNlKTsKUEsBAhQDFAAAAAAAvDZqTN\/1FdQyAAAAMgAAAAcAAAAAAAAAAAAAALaBAAAAAHVzZXIuanNQSwUGAAA
AAAEAAQA1AAAAVwAAAAAA"}}

Failed to connect to 0.0.0.0 port 4444: Address not available in D:\xampp\htdocs\php-webdriver\php-webd
river\lib\Remote\HttpCommandExecutor.php:292
Stack trace:
#0 D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\
Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#1 D:\xampp\htdocs\php-webdriver\php-webdriver\example.php(14): Facebook\WebDriver\Remote\RemoteWebDriv
er::create('http://0.0.0.0:...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 5000)
#2 {main}
  thrown in D:\xampp\htdocs\php-webdriver\php-webdriver\lib\Remote\HttpCommandExecutor.php on line 292

feb2018@adminxA MINGW32 /d/xampp/htdocs/php-webdriver/php-webdriver (community)

```

**Comment by flik** [comment]
I get one success. I replaced selenium server version from **selenium-server-standalone-3.9.1** to **selenium-server-standalone-3.3.0**
This was an issue. Now, above errors fixed. :)
