### ISSUE TITLE
UnknownServer error in php

### ISSUE THREAD

**Issue by BoardofEd** [facebook/php-webdriver#584]
### What are you trying to achieve? (Expected behavior)
To run the phpsample without errors.

### What do you get instead? (Actual behavior)
```
PHP Fatal error:  Uncaught exception 'Facebook\WebDriver\Exception\UnknownServerException' in /home/naaiporg/Selenium-Setup-Webdriver/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:118
Stack trace:
#0 /home/naaiporg/Selenium-Setup-Webdriver/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php(287): Facebook\WebDriver\Exception\WebDriverException::throwException(13, NULL, Array)
#1 /home/naaiporg/Selenium-Setup-Webdriver/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(97): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#2 /home/naaiporg/public_html/TestDriver.php(15): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://naaip.or...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 5000)
#3 {main}
  thrown in /home/naaiporg/Selenium-Setup-Webdriver/vendor/facebook/webdriver/lib/Exception/WebDriverException.php on line 118
```

### How could the issue be reproduced? (Steps to reproduce)
```php
<?php
// An example of using php-webdriver.
// Do not forget to run composer install before and also have Selenium server started and listening on port 4444.
namespace Facebook\WebDriver;
ini_set("log_errors", 1);

require_once('/home/naaiporg/Selenium-Setup/vendor/autoload.php');
require_once('/home/naaiporg/Selenium-Setup-Webdriver/vendor/autoload.php');
use Facebook\WebDriver\Chrome\ChromeDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
// start Chrome with 5 second timeout
$host = 'http://localhost:4444/wd/hub/'; // this is the default
$capabilities = DesiredCapabilities::chrome();
$driver = RemoteWebDriver::create($host, $capabilities, 5000);
// navigate to 'http://www.seleniumhq.org/'
$driver->get('https://www.seleniumhq.org/');
// adding cookie
$driver->manage()->deleteAllCookies();
$cookie = new Cookie('cookie_name', 'cookie_value');
$driver->manage()->addCookie($cookie);
$cookies = $driver->manage()->getCookies();
print_r($cookies);
// click the link 'About'
$link = $driver->findElement(
    WebDriverBy::id('menu_about')
);
$link->click();
// wait until the page is loaded
$driver->wait()->until(
    WebDriverExpectedCondition::titleContains('About')
);
// print the title of the current page
echo "The title is '" . $driver->getTitle() . "'\n";
// print the URI of the current page
echo "The current URI is '" . $driver->getCurrentURL() . "'\n";
// write 'php' in the search box
$driver->findElement(WebDriverBy::id('q'))
    ->sendKeys('php') // fill the search box
    ->submit(); // submit the whole form
// wait at most 10 seconds until at least one result is shown
$driver->wait(10)->until(
    WebDriverExpectedCondition::presenceOfAllElementsLocatedBy(
        WebDriverBy::className('gsc-result')
    )
);
// close the browser
$driver->quit();
?>

```
### Details

* Php-webdriver version: Dev-Master
* PHP version: 5.6.36
* Selenium server version: 2.48.2
* Operating system: CentOS 6.9
* Browser used + version: Chrome

**Comment by OndraM** [comment]
Hi,
from the versions info you provided, it looks like you are using incompatible selenium + chrome.

Please ty to use newer Chrome with compatible [Chromedrive](https://sites.google.com/a/chromium.org/chromedriver/) and latest Selenium server.

**Comment by BoardofEd** [comment]
Thanks Ondra!  Can you tell me wht versions of Chromedrive I should be using for this?  Chromedrive 2.40 works with the latest version of Selenium?

**Comment by OndraM** [comment]
Yes.
