### ISSUE TITLE
Chrome not open anything

### ISSUE THREAD

**Issue by jamiakdeploy** [facebook/php-webdriver#616]
### What are you trying to achieve? (Expected behavior)
Opening a website

### What do you get instead? (Actual behavior)
Chrome opens and shows "data:," in the location bar and nothing happens until PHP times out

### How could the issue be reproduced? (Steps to reproduce)
https://github.com/facebook/php-webdriver/blob/community/example.php

### Details

* Php-webdriver version: latest from this repo from yesterday
* PHP version: 7.2.8
* Selenium server version: 3.9.1
* Operating system: OSX latest
* Browser used + version: ChromeDriver 2.44.609545

**Console output from selenium driver**
```
❯ java -jar ~/Downloads/selenium-server-standalone-3.9.1.jar
14:59:45.738 INFO - Selenium build info: version: '3.9.1', revision: '63f7b50'
14:59:45.739 INFO - Launching a standalone Selenium Server on port 4444
2018-11-22 14:59:45.876:INFO::main: Logging initialized @411ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-11-22 14:59:45.982:INFO:osjs.Server:main: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T22:27:37+01:00, git hash: 82b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-11-22 14:59:46.002:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@48f278eb{/,null,STARTING} has uncovered http methods for path: /
2018-11-22 14:59:46.006:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@48f278eb{/,null,AVAILABLE}
2018-11-22 14:59:46.031:INFO:osjs.AbstractConnector:main: Started ServerConnector@4145bad8{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2018-11-22 14:59:46.032:INFO:osjs.Server:main: Started @567ms
14:59:46.032 INFO - Selenium Server is up and running on port 4444
2018-11-22 15:00:12.586:INFO:osjshC.ROOT:qtp112797691-15: org.openqa.selenium.remote.server.WebDriverServlet-152aa092: Initialising WebDriverServlet
15:00:12.641 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@7711f9c1
15:00:12.644 INFO - /session: Executing POST on /session (handler: BeginSession)
15:00:12.706 INFO - Capabilities are: Capabilities {browserName: chrome}
15:00:12.707 INFO - Capabilities {browserName: chrome} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5) on port 1085
Only local connections are allowed.
```

**Console output from php**
```
❯ php index.php

Fatal error: Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY"}}

Operation timed out after 30000 milliseconds with 0 bytes received in /Users/user/test/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:292
Stack trace:
#0 /Users/user/test/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand))
#1 /Users/user/test/index.php(18): Facebook\WebDriver\Remote\RemoteWebDriver::create('http://localhos...', Object(Facebook\WebDriver\Remote\DesiredCapabilities), 5000)
#2 {main}
  thrown in /Users/user/test/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php on line 292
```

**Comment by jamiakdeploy** [comment]
Nevermind - updating chrome itself fixed it instantly... 

FOR PEOPLE IN THE FUTURE FINDING THIS WITH THE SAME ISSUE:

**UPDATE CHROME ON YOUR SYSTEM! ;)**

as in literally start chrome or the window it opens and hit update!
